spring.application.name=flatox-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/flatbox_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
server.address=0.0.0.0