create table budget_plans (fiscal_year_end date not null, fiscal_year_start date not null, total_allocated_expense numeric(15,2) not null, total_estimated_revenue numeric(15,2) not null, apartment_id bigint not null, created_at timestamp(6), created_by_user_id bigint, id bigint generated by default as identity, primary key (id));
alter table if exists budget_plans add constraint FKjl4v7seixfqutgotj5ci8quea foreign key (apartment_id) references apartments;
alter table if exists budget_plans add constraint FKag7rrd4qejfvfgl6le3exoao7 foreign key (created_by_user_id) references users;
