create table budget_items (actual_spending numeric(12,2), allocated_amount numeric(12,2) not null, budget_plan_id bigint not null, id bigint generated by default as identity, category varchar(255) not null, primary key (id));
alter table if exists budget_items add constraint FKd5oojwsmysf14jrj9x91ya9q3 foreign key (budget_plan_id) references budget_plans;
