create table expenses (amount numeric(12,2) not null, expense_date date not null, apartment_id bigint not null, budget_item_id bigint, created_at timestamp(6), id bigint generated by default as identity, recorded_by_user_id bigint, vendor_id bigint, category varchar(255) not null, description TEXT, invoice_url varchar(255), receipt_url varchar(255), primary key (id));
alter table if exists expenses add constraint FKbkwwpspbvv5ackr56944j4v66 foreign key (apartment_id) references apartments;
alter table if exists expenses add constraint FKn8eye0078oo4w4q6duveafmy foreign key (budget_item_id) references budget_items;
alter table if exists expenses add constraint FK883viqf8woaqrf95oywcdkp1o foreign key (recorded_by_user_id) references users;
alter table if exists expenses add constraint FK3bxuel18l0ajrn465dtmbul6n foreign key (vendor_id) references vendors;
