create table accounting_ledger (amount numeric(12,2) not null, apartment_id bigint not null, created_at timestamp(6), expense_id bigint, id bigint generated by default as identity, transaction_id uuid, system_hash varchar(64) not null, account_name varchar(255) not null, description TEXT, entry_type varchar(255) not null check ((entry_type in ('DEBIT','CREDIT'))), primary key (id));
alter table if exists accounting_ledger add constraint FK45jetm48or5j6jyqghoeo4s4n foreign key (apartment_id) references apartments;
alter table if exists accounting_ledger add constraint FK4df2ivfb8hm3gywexo7tmm56i foreign key (expense_id) references expenses;
alter table if exists accounting_ledger add constraint FKejrnrupngav1th69wumg39fk4 foreign key (transaction_id) references transactions;
