create table billing_template_items (
    id bigint generated by default as identity,
    template_id bigint not null,
    label varchar(255) not null,
    amount numeric(12,2) not null,
    primary key (id),
    constraint fk_billing_template_items_template foreign key (template_id) references billing_templates
);

create table maintenance_bill_items (
    id bigint generated by default as identity,
    bill_id bigint not null,
    label varchar(255) not null,
    amount numeric(12,2) not null,
    primary key (id),
    constraint fk_maintenance_bill_items_bill foreign key (bill_id) references maintenance_bills
);
