-- ============================================================
-- V18: AI Expense Assistant schema extensions
-- ============================================================

-- 1. Add status + AI fields to existing expenses table
ALTER TABLE expenses ADD COLUMN status VARCHAR(20) DEFAULT 'CONFIRMED';
ALTER TABLE expenses ADD COLUMN invoice_number VARCHAR(255);
ALTER TABLE expenses ADD COLUMN bill_date DATE;
ALTER TABLE expenses ADD COLUMN due_date DATE;
ALTER TABLE expenses ADD COLUMN tax_amount NUMERIC(12,2);
ALTER TABLE expenses ADD COLUMN document_type VARCHAR(100);
ALTER TABLE expenses ADD COLUMN ai_confidence DOUBLE PRECISION;
ALTER TABLE expenses ADD COLUMN ai_raw_json TEXT;
ALTER TABLE expenses ADD COLUMN source VARCHAR(20) DEFAULT 'MANUAL';

-- 2. Vendor recognition rules for deterministic rule engine
CREATE TABLE vendor_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartment_id BIGINT NOT NULL,
    keyword VARCHAR(255) NOT NULL,
    vendor_id BIGINT,
    category VARCHAR(100) NOT NULL,
    confidence DOUBLE PRECISION DEFAULT 1.0,
    created_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_vendor_rules_apartment FOREIGN KEY (apartment_id) REFERENCES apartments(id),
    CONSTRAINT fk_vendor_rules_vendor FOREIGN KEY (vendor_id) REFERENCES vendors(id)
);

-- 3. AI extraction corrections (for future learning)
CREATE TABLE ai_corrections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartment_id BIGINT NOT NULL,
    expense_id BIGINT NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    original_value TEXT,
    corrected_value TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_ai_corrections_apartment FOREIGN KEY (apartment_id) REFERENCES apartments(id),
    CONSTRAINT fk_ai_corrections_expense FOREIGN KEY (expense_id) REFERENCES expenses(id)
);

-- 4. Indexes for performance
CREATE INDEX idx_vendor_rules_apartment ON vendor_rules(apartment_id);
CREATE INDEX idx_vendor_rules_keyword ON vendor_rules(keyword);
CREATE INDEX idx_ai_corrections_expense ON ai_corrections(expense_id);
CREATE INDEX idx_expenses_status ON expenses(status);
CREATE INDEX idx_expenses_invoice_number ON expenses(invoice_number);
