create table apartments (created_at timestamp(6),
 id bigint generated by default as identity,
  address varchar(255), city varchar(255),
   name varchar(255), pincode varchar(255),
    state varchar(255), primary key (id));
