create table flats (square_footage float(53), apartment_id bigint, id bigint generated by default as identity, bhk_type varchar(255), block_name varchar(255), flat_number varchar(255), status varchar(255) check ((status in ('VACANT','OCCUPIED','RENTED'))), primary key (id));
alter table if exists flats add constraint FKluid8caoo7tqtnyre83do6tkm foreign key (apartment_id) references apartments;
