create table users (apartment_id bigint, created_at timestamp(6), 
flat_id bigint, 
id bigint generated by default as identity, approval_status varchar(255) check ((approval_status in ('PENDING','APPROVED','REJECTED'))), email varchar(255) unique, full_name varchar(255), owner_status varchar(255), phone varchar(255) not null unique, role varchar(255) check ((role in ('ADMIN','RESIDENT','WATCHMAN','INVENTORY_MANAGER'))), user_type varchar(255), primary key (id));
alter table if exists users add constraint FKo77vtey7gpjuiuy0x8t8mkjod foreign key (apartment_id) references apartments;
alter table if exists users add constraint FKbsdf463u1l1k9vk9u17ci1u7j foreign key (flat_id) references flats;
