create table vendors (apartment_id bigint not null, created_at timestamp(6), id bigint generated by default as identity, bank_account_details TEXT, company_name varchar(255) not null, contact_person varchar(255), email varchar(255), phone varchar(255), primary key (id));
alter table if exists vendors add constraint FKih5dfl6vf9facymnghdlc1r88 foreign key (apartment_id) references apartments;
